# -*- coding: utf-8 -*-
"""Programming Final Program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQRizr_GuKw2W2CAYpPg7zQKeEI5R66l
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind

df = pd.read_csv("/content/National_Syndromic_Surveillance_Program_(NSSP)_Mental_Health-Related_Emergency_Department_Visit_Rates_20251126.csv")

df['month_end'] = pd.to_datetime(df['month_end'])

df.head()

df['demographics_type'].unique()

df['demographics_values'].unique()

df['condition'].unique()

df.columns

df_wide = (
    df
    .pivot_table(
        index='month_end',
        columns=['condition', 'demographics_values'],
        values='rate_per_100000_visits'
    )
    .reset_index()
)

df_wide.head()

plt.figure(figsize=(14,6))
sns.lineplot(
    data=df,
    x='month_end',
    y='rate_per_100000_visits'
)
plt.title('Mental Health–Related ED Visit Rates Over Time')
plt.xlabel('Month')
plt.ylabel('Rate per 100,000 Visits')
plt.show()

plt.figure(figsize=(14,6))
sns.lineplot(
    data=df,
    x='month_end',
    y='rate_per_100000_visits',
    hue='condition'
)
plt.title('ED Visit Rates Over Time by Condition')
plt.xlabel('Month')
plt.ylabel('Rate per 100,000 Visits')
plt.legend(title='Condition')
plt.show()

df_age = df[df['demographics_type'] == 'Age'][['month_end', 'condition','demographics_values', 'rate_per_100000_visits']].rename(
    columns={'demographics_values':'AgeGroup', 'rate_per_100000_visits':'rate_age'}
)

age_groups = ['12-17 years', '18-34 years','35-64 years', '65+ years']
conditions = ['Anxiety Disorders', 'Any Mental Health', 'Bipolar Disorders','Depressive Disorders', 'Schizophrenia Spectrum Disorders','Suspected Suicide Attempts','Trauma and Stressor-related Disorders']
for cond in conditions:
    df_cond_age = df_age[(df_age['condition'] == cond) &
                         (df_age['AgeGroup'].isin(age_groups))]

    plt.figure(figsize=(14,6))
    sns.lineplot(
        data=df_cond_age,
        x='month_end',
        y='rate_age',
        hue='AgeGroup',
        linewidth=2
    )

    plt.title(f'ED Visit Rates by Age Group – {cond}')
    plt.xlabel('Month')
    plt.ylabel('Rate per 100,000 ED Visits')
    plt.legend(title='Age Group')
    plt.tight_layout()
    plt.show()

race_groups = [
    'AI/AN, NH', 'Asian, NH', 'Black, NH', 'Hispanic',
    'NHOPI, NH', 'White, NH', 'Multiple/Other, NH'
]

df_race = df[(df['demographics_type'] == 'RaceEthnicity') &
             (df['demographics_values'].isin(race_groups))]

plt.figure(figsize=(12,6))
sns.barplot(
    data=df_race,
    x='demographics_values',
    y='rate_per_100000_visits',
    errorbar=None
)

plt.title('Mean Mental Health–Related ED Visit Rates by Race/Ethnicity')
plt.xlabel('Race/Ethnicity')
plt.ylabel('Rate per 100,000 ED Visits')
plt.show()

df_sex = df[df['demographics_type'] == 'Sex']

plt.figure(figsize=(8,6))
sns.barplot(
    data=df_sex,
    x='demographics_values',
    y='rate_per_100000_visits',
    errorbar=None
)

plt.title('Mean Mental Health–Related ED Visit Rates by Sex')
plt.xlabel('Sex')
plt.ylabel('Rate per 100,000 ED Visits')
plt.show()

conditions = [
    "Anxiety Disorders",
    "Depressive Disorders",
    "Suspected Suicide Attempts"
]

results = []

for cond in conditions:
    demo_sub = df[
        (df["condition"] == cond) &
        (df["demographics_type"] == "Sex")
    ]

    male = demo_sub[demo_sub["demographics_values"] == "Male"]
    female = demo_sub[demo_sub["demographics_values"] == "Female"]

    t_stat, p_val = ttest_ind(
        male["rate_per_100000_visits"],
        female["rate_per_100000_visits"],
        equal_var=False
    )

    results.append({
        "Condition": cond,
        "Mean_Male": male["rate_per_100000_visits"].mean(),
        "Mean_Female": female["rate_per_100000_visits"].mean(),
        "t_stat": t_stat,
        "p_value": p_val
    })

ttest_results = pd.DataFrame(results)
print(ttest_results)

"""Independent-samples t-tests indicated statistically significant differences in average ED visit rates between males and females for anxiety disorders, depressive disorders, and suspected suicide attempts (all ps < .001), with females showing higher mean rates across all conditions.

These tests compare average rates across the full time period and do not account for temporal trends. Results are interpreted as descriptive and exploratory rather than causal.
"""

plt.figure(figsize=(14,6))
sns.lineplot(
    data=df_sex,
    x='month_end',
    y='rate_per_100000_visits',
    hue='demographics_values',
    errorbar=None
)

plt.title('ED Visit Rates Over Time by Sex')
plt.xlabel('Month')
plt.ylabel('Rate per 100,000 ED Visits')
plt.legend(title='Sex')
plt.show()

df_age = df[df['demographics_type'] == 'Age'][['month_end', 'condition','demographics_values', 'rate_per_100000_visits']].rename(
    columns={'demographics_values':'AgeGroup', 'rate_per_100000_visits':'rate_age'}
)

df_sex = df[df['demographics_type'] == 'Sex'][['month_end', 'condition','demographics_values', 'rate_per_100000_visits']].rename(
    columns={'demographics_values':'Sex', 'rate_per_100000_visits':'rate_sex'}
)

df_race = df[df['demographics_type'] == 'RaceEthnicity'][['month_end', 'condition','demographics_values', 'rate_per_100000_visits']].rename(
    columns={'demographics_values':'RaceEthnicity', 'rate_per_100000_visits':'rate_race'}
)

df_merge = pd.merge(df_age, df_sex, on=['month_end', 'condition'], how='outer')
df_merge = pd.merge(df_merge, df_race, on=['month_end', 'condition'], how='outer')

age_groups = df_merge['AgeGroup'].dropna().unique()
sex_groups = df_merge['Sex'].dropna().unique()
race_groups = df_merge['RaceEthnicity'].dropna().unique()
conditions = df_merge['condition'].dropna().unique()

df_filtered = df_merge[
    (df_merge['AgeGroup'].isin(age_groups)) &
    (df_merge['Sex'].isin(sex_groups)) &
    (df_merge['RaceEthnicity'].isin(race_groups)) &
    (df_merge['condition'].isin(conditions))
]

conditions = ['Anxiety Disorders', 'Any Mental Health', 'Bipolar Disorders','Depressive Disorders', 'Schizophrenia Spectrum Disorders','Suspected Suicide Attempts','Trauma and Stressor-related Disorders']
for cond in conditions:
    df_cond_sex = df_sex[df_sex['condition'] == cond]

    plt.figure(figsize=(14,6))
    sns.lineplot(
        data=df_cond_sex,
        x='month_end',
        y='rate_sex',
        hue='Sex',  # Male vs Female
        linewidth=2
    )

    plt.title(f'ED Visit Rates by Sex – {cond}')
    plt.xlabel('Month')
    plt.ylabel('Rate per 100,000 ED Visits')
    plt.legend(title='Sex')
    plt.tight_layout()
    plt.show()

df_race = df[df['demographics_type'] == 'RaceEthnicity']

race_groups = ['Hispanic', 'Asian, NH', 'Black, NH', 'White, NH']
conditions = ['Anxiety Disorders', 'Any Mental Health', 'Bipolar Disorders','Depressive Disorders', 'Schizophrenia Spectrum Disorders','Suspected Suicide Attempts','Trauma and Stressor-related Disorders']
for cond in conditions:
    df_cond_race = df_race[(df_race['condition'] == cond) &
                           (df_race['demographics_values'].isin(race_groups))]

    plt.figure(figsize=(14,6))
    sns.lineplot(
        data=df_cond_race,
        x='month_end',
        y='rate_per_100000_visits',
        hue='demographics_values',
        linewidth=2
    )

    plt.title(f'ED Visit Rates by Race/Ethnicity – {cond}')
    plt.xlabel('Month')
    plt.ylabel('Rate per 100,000 ED Visits')
    plt.legend(title='Race/Ethnicity')
    plt.tight_layout()
    plt.show()

df_age = df[df['demographics_type'] == 'Age'].copy()

age_groups = ['12-17 years', '18-34 years', '35-64 years', '65+ years']
conditions = [
    'Anxiety Disorders', 'Any Mental Health', 'Bipolar Disorders',
    'Depressive Disorders', 'Schizophrenia Spectrum Disorders',
    'Suspected Suicide Attempts', 'Trauma and Stressor-related Disorders'
]

for cond in conditions:
    df_cond_age = df_age[
        (df_age['condition'] == cond) &
        (df_age['demographics_values'].isin(age_groups))
    ]

    plt.figure(figsize=(14,6))
    sns.lineplot(
        data=df_cond_age,
        x='month_end',
        y='rate_per_100000_visits',
        hue='demographics_values',
        linewidth=2,
        errorbar=None
    )

    plt.title(f'ED Visit Rates by Age Group – {cond}')
    plt.xlabel('Month')
    plt.ylabel('Rate per 100,000 ED Visits')
    plt.legend(title='Age Group')
    plt.tight_layout()
    plt.show()

# What conditions are present
print(df['condition'].value_counts())

# What demographics are present
print(df_merge[['AgeGroup','Sex','RaceEthnicity']].nunique())

# Time range
print(df['month_end'].min(), df['month_end'].max())